# Generated by Django 4.0.5 on 2022-06-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='papers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('publisher', models.TextField()),
                ('publication_date', models.DateTimeField()),
                ('doi', models.CharField(max_length=50)),
                ('source_type', models.CharField(max_length=50)),
                ('work_type', models.CharField(max_length=50)),
                ('source_quartile', models.IntegerField()),
                ('authors_field', models.TextField()),
                ('citations', models.TextField()),
            ],
        ),
    ]
