# Generated by Django 4.0.5 on 2022-06-17 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papers',
            old_name='authors_field',
            new_name='authors_affils',
        ),
    ]
