# Generated by Django 4.0.5 on 2022-06-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_authors_field_papers_authors_affils'),
    ]

    operations = [
        migrations.DeleteModel(
            name='papers',
        ),
    ]
